// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: pkg/model_pb/analysis.proto

package model_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentHash   string                 `protobuf:"bytes,1,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	ContentText   string                 `protobuf:"bytes,2,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisInput) Reset() {
	*x = AnalysisInput{}
	mi := &file_pkg_model_pb_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisInput) ProtoMessage() {}

func (x *AnalysisInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_pb_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisInput.ProtoReflect.Descriptor instead.
func (*AnalysisInput) Descriptor() ([]byte, []int) {
	return file_pkg_model_pb_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisInput) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *AnalysisInput) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *AnalysisInput) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AnalysisInput) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type NeuralFeatures struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FakenessScore  float32                `protobuf:"fixed32,1,opt,name=fakeness_score,json=fakenessScore,proto3" json:"fakeness_score,omitempty"`
	EmotionScore   float32                `protobuf:"fixed32,2,opt,name=emotion_score,json=emotionScore,proto3" json:"emotion_score,omitempty"`
	VisualArtifact bool                   `protobuf:"varint,3,opt,name=visual_artifact,json=visualArtifact,proto3" json:"visual_artifact,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NeuralFeatures) Reset() {
	*x = NeuralFeatures{}
	mi := &file_pkg_model_pb_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeuralFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeuralFeatures) ProtoMessage() {}

func (x *NeuralFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_pb_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeuralFeatures.ProtoReflect.Descriptor instead.
func (*NeuralFeatures) Descriptor() ([]byte, []int) {
	return file_pkg_model_pb_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *NeuralFeatures) GetFakenessScore() float32 {
	if x != nil {
		return x.FakenessScore
	}
	return 0
}

func (x *NeuralFeatures) GetEmotionScore() float32 {
	if x != nil {
		return x.EmotionScore
	}
	return 0
}

func (x *NeuralFeatures) GetVisualArtifact() bool {
	if x != nil {
		return x.VisualArtifact
	}
	return false
}

var File_pkg_model_pb_analysis_proto protoreflect.FileDescriptor

const file_pkg_model_pb_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/model_pb/analysis.proto\x12\bmodel_pb\"\x8f\x01\n" +
	"\rAnalysisInput\x12!\n" +
	"\fcontent_hash\x18\x01 \x01(\tR\vcontentHash\x12!\n" +
	"\fcontent_text\x18\x02 \x01(\tR\vcontentText\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"\x85\x01\n" +
	"\x0eNeuralFeatures\x12%\n" +
	"\x0efakeness_score\x18\x01 \x01(\x02R\rfakenessScore\x12#\n" +
	"\remotion_score\x18\x02 \x01(\x02R\femotionScore\x12'\n" +
	"\x0fvisual_artifact\x18\x03 \x01(\bR\x0evisualArtifactB=Z;gitlab.com/hyperpolymath/disinfo-nsai-detector/pkg/model_pbb\x06proto3"

var (
	file_pkg_model_pb_analysis_proto_rawDescOnce sync.Once
	file_pkg_model_pb_analysis_proto_rawDescData []byte
)

func file_pkg_model_pb_analysis_proto_rawDescGZIP() []byte {
	file_pkg_model_pb_analysis_proto_rawDescOnce.Do(func() {
		file_pkg_model_pb_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_model_pb_analysis_proto_rawDesc), len(file_pkg_model_pb_analysis_proto_rawDesc)))
	})
	return file_pkg_model_pb_analysis_proto_rawDescData
}

var file_pkg_model_pb_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_model_pb_analysis_proto_goTypes = []any{
	(*AnalysisInput)(nil),  // 0: model_pb.AnalysisInput
	(*NeuralFeatures)(nil), // 1: model_pb.NeuralFeatures
}
var file_pkg_model_pb_analysis_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_model_pb_analysis_proto_init() }
func file_pkg_model_pb_analysis_proto_init() {
	if File_pkg_model_pb_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_model_pb_analysis_proto_rawDesc), len(file_pkg_model_pb_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_model_pb_analysis_proto_goTypes,
		DependencyIndexes: file_pkg_model_pb_analysis_proto_depIdxs,
		MessageInfos:      file_pkg_model_pb_analysis_proto_msgTypes,
	}.Build()
	File_pkg_model_pb_analysis_proto = out.File
	file_pkg_model_pb_analysis_proto_goTypes = nil
	file_pkg_model_pb_analysis_proto_depIdxs = nil
}
